stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/<your-namespace>/snapp-webapp

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build --build-arg APP_VERSION=$CI_COMMIT_TAG -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
  only:
    - tags

deploy:
  stage: deploy
  image: bitnamilegacy/kubectl:1.34
  script:
    - kubectl set image deployment/snapp-webapp snapp-webapp=$IMAGE_NAME:$CI_COMMIT_TAG -n snapp-project
    - kubectl rollout status deployment/snapp-webapp -n snapp-project
  only:
    - tags
