{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingressNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
      ports:
        - protocol: TCP
          port: {{ $.Values.service.targetPort }}
    {{- end }}
    - from:
        - podSelector:
            matchLabels:
              app: load-generator
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    # DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
    # HTTPS Outbound
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
{{- end }}